"""Nested cross-fitted, cross-calibrated OOF risk scores — DESIGN_FREEZE.md §3.

For each outer fold k:
  - the base model is fit on outer-training data (folds != k) with that fold's
    hyperparameters (selected by inner CV inside outer-training during Layer 1;
    reread from the persisted stability artifact so the exact same procedure is
    reused rather than silently re-derived);
  - the calibrator (isotonic, frozen in §3) is fit on INNER-OOF scores
    generated wholly within outer-training data: each inner-OOF score comes
    from a model that never saw its inner fold, and no model involved ever saw
    fold k. This is the nested scheme; the naive "calibrate on other folds'
    OOF scores" alternative is leaky because those scores come from models
    trained on fold k;
  - base model + calibrator are applied to fold k.

The result: every RISK-DEV customer carries a calibrated PD produced by
machinery that never touched their own label. tests/test_oof_no_leakage.py
verifies this behaviorally (flipping a fold's labels must not move that fold's
scores) and by determinism (fold predictions are reproducible from scratch).
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.isotonic import IsotonicRegression
from sklearn.model_selection import StratifiedKFold

from . import config
from .risk_models import fit_lgbm, tune_lgbm


def outer_folds(X: pd.DataFrame, y: pd.Series):
    """The frozen outer-fold structure — identical to Layer 1's stability CV
    (same splitter, same seed), so per-fold artifacts line up."""
    skf = StratifiedKFold(n_splits=config.N_OUTER_FOLDS, shuffle=True,
                          random_state=config.SEED_SPLIT)
    return list(skf.split(X, y))


def load_per_fold_params(path=None) -> dict[int, dict]:
    """Per-outer-fold LightGBM params chosen during Layer 1's nested CV."""
    path = path or (config.ARTIFACTS_DIR / "stability_outer_cv.csv")
    stab = pd.read_csv(path)
    rows = stab[stab["model"] == "lgbm_mono"]
    return {
        int(r["fold"]): {
            "num_leaves": int(r["chosen_num_leaves"]),
            "min_child_samples": int(r["chosen_min_child_samples"]),
            "n_estimators": int(r["chosen_n_estimators"]),
        }
        for _, r in rows.iterrows()
    }


def _fit_calibrator(Xtr: pd.DataFrame, ytr: pd.Series, params: dict,
                    seed: int) -> IsotonicRegression:
    """Isotonic calibrator fit on inner-OOF scores of the OUTER-TRAINING data.

    Every inner-OOF score is produced by a model fit on inner-training rows
    only; the calibrator therefore never sees a score generated by a model
    that observed the row being calibrated — and, because everything here
    lives inside outer-training data, never anything from the outer fold.
    """
    skf = StratifiedKFold(n_splits=config.N_INNER_FOLDS, shuffle=True,
                          random_state=seed)
    inner_oof = np.full(len(Xtr), np.nan)
    for tr, va in skf.split(Xtr, ytr):
        m = fit_lgbm(Xtr.iloc[tr], ytr.iloc[tr], params)
        inner_oof[va] = m.predict_proba(Xtr.iloc[va])[:, 1]
    assert not np.isnan(inner_oof).any(), "inner cross-fit left gaps"
    iso = IsotonicRegression(y_min=0.0, y_max=1.0, out_of_bounds="clip")
    iso.fit(inner_oof, ytr.to_numpy())
    return iso


def produce_calibrated_oof(X: pd.DataFrame, y: pd.Series,
                           per_fold_params: dict[int, dict] | None = None,
                           verbose: bool = True,
                           folds: list | None = None) -> pd.DataFrame:
    """Returns a frame indexed like X with columns fold / oof_raw / oof_cal.

    `folds` may be injected (tests use this to hold the fold structure fixed
    while perturbing labels); by default the frozen splitter derives them.
    """
    out = pd.DataFrame(index=X.index,
                       columns=["fold", "oof_raw", "oof_cal"], dtype=float)
    for k, (tr, va) in enumerate(folds if folds is not None else outer_folds(X, y)):
        Xtr, ytr = X.iloc[tr], y.iloc[tr]
        if per_fold_params is not None:
            params = per_fold_params[k]
        else:
            params, _ = tune_lgbm(Xtr, ytr)  # full nested tuning from scratch
        base = fit_lgbm(Xtr, ytr, params)
        calib = _fit_calibrator(Xtr, ytr, params, seed=config.SEED_MODEL + k)
        raw = base.predict_proba(X.iloc[va])[:, 1]
        out.iloc[va, out.columns.get_loc("fold")] = k
        out.iloc[va, out.columns.get_loc("oof_raw")] = raw
        out.iloc[va, out.columns.get_loc("oof_cal")] = calib.predict(raw)
        if verbose:
            print(f"  fold {k}: base+calibrator done "
                  f"(mean raw {raw.mean():.4f} -> cal {out.iloc[va]['oof_cal'].mean():.4f})")
    return out
